### ISSUE TITLE
How to use AVX2 only for hashmap/set, and use stable hash for hash128/64/32

### ISSUE THREAD

**Issue by xxaier** [ogxd/gxhash#29]
how to use AVX2 only for hashmap/set ，and use stable hash for hash128/64/32

**Comment by ogxd** [comment]
Hello @xxaier, 

Can you share a little bit about your usecase? Why would you need both?

This is currently not possible, as using the 'avx2' makes the whole binary use AVX2. Allowing both would imply to add specific APIs like `GxHasherAVX2`, `GxHashBuilderAVX2`, `GxHashMapAVX2` and `gxhash32/64/128_avx2` on top of the existing APIs, making the package and documentation a lot more complex for something I feel really is an edge case.

If others are interested in this please raise you hand and share a little bit about your usecase.

**Comment by ogxd** [comment]
Maybe this would work, but I haven't tested it:

```toml
[dependencies]
gxhash = { package = "gxhash", version = "*" }
gxhash_avx2 = { package = "gxhash", version = "*", features = ["avx2"] }
```
